# Generated by Django 6.0.7 on 2026-07-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='preffered_time',
            new_name='prefered_time',
        ),
        migrations.AlterField(
            model_name='ride',
            name='flexibility',
            field=models.IntegerField(choices=[('5', '5 minutes'), ('10', '10 minutes'), ('15', '15 minutes')]),
        ),
    ]
